### ISSUE TITLE
KeyError: '-' using VCF mode

### ISSUE THREAD

**Issue by gkumar09** [gantzgraf/CrossMap#6]
Hi,
Used following command to liftover vcf file from GRCh37 to 38.

CrossMap.py vcf ~/bioinfo_tools/vcf-liftover/GRCh37_to_GRCh38.chain.gz final.combined_cancer_tcga.fixed.vcf.gz Homo_sapiens.GRCh38.dna.primary_assembly.fa hg38.final.combined_cancer_tcga.fixed.vcf

and got the following error:
Traceback (most recent call last):
  File "/usr/bin/CrossMap.py", line 1932, in <module>
    crossmap_vcf_file(mapping = mapTree, infile= in_file, outfile = out_file, liftoverfile = sys.argv[2], refgenome = genome_file)
  File "/usr/bin/CrossMap.py", line 608, in crossmap_vcf_file
    fields[4] = revcomp_DNA(fields[4], True)
  File "/usr/bin/CrossMap.py", line 106, in revcomp_DNA
    return ''.join([complement[base] for base in reversed(seq)])
  File "/usr/bin/CrossMap.py", line 106, in <listcomp>
    return ''.join([complement[base] for base in reversed(seq)])
KeyError: '-'

Can you please help.
Thanks

**Comment by brianpenghe** [comment]
Same error here
